auth_enabled: false
server:
  http_listen_port: 3300
distributor:
  receivers:
    otlp:
      protocols:
        http: 
         endpoint: "0.0.0.0:4318"
        grpc: 

ingester:
  trace_idle_period: 10s
  max_block_duration: 5m
compactor:
  compaction:
    compaction_window: 1h
    max_compaction_objects: 1000000
    block_retention: 1h
    compacted_block_retention: 10m
storage:
  trace:
    backend: local
    wal:
      path: /opt/workspace/devops/tempo/wal
    local:
      path: /opt/workspace/devops/tempo/blocks
    pool:
      max_workers: 100
      queue_depth: 10000

